/**
 * Curated icon palette for custom presence statuses.
 *
 * Stored as a string id (`CustomRoleIconId`) in user data so the persisted
 * shape doesn't carry a component reference. Every visual surface that
 * needs to render the icon (presence pill, dropdown menu, Settings → My
 * Roles status editor) resolves the glyph through `resolveCustomRoleIcon`.
 *
 * `CUSTOM_ROLE_ICON_IDS` is ordered by theme — work, focus, rest, comms,
 * travel, nature, science — because the picker lays it out as a grid and
 * alphabetical order would scatter related glyphs. Ids double as the
 * picker's search text, so each one is a plain English word.
 *
 * Adding a glyph here puts it in whatever chunk imports this module, which
 * includes the navigation sidebar. Keep the palette curated.
 */
import {
  Airplane01Icon,
  Alien01Icon,
  AnchorIcon,
  AtomicPowerIcon,
  BatteryFullIcon,
  Bicycle01Icon,
  Book01Icon,
  Bookmark01Icon,
  BotIcon,
  BrainIcon,
  Briefcase01Icon,
  Bug01Icon,
  Building01Icon,
  Calendar03Icon,
  Camera01Icon,
  Car01Icon,
  ChampionIcon,
  ChartLineData01Icon,
  Clock01Icon,
  CloudIcon,
  CodeXmlIcon,
  Coffee01Icon,
  CompassIcon,
  ComputerIcon,
  ComputerTerminal01Icon,
  CrownIcon,
  Database01Icon,
  DiamondIcon,
  Dumbbell01Icon,
  FavouriteIcon,
  FeatherIcon,
  FireIcon,
  Flag01Icon,
  GameController01Icon,
  GhostIcon,
  GiftIcon,
  GitBranchIcon,
  Globe02Icon,
  HeadphonesIcon,
  Home01Icon,
  type IconSvgElement,
  Idea01Icon,
  Key01Icon,
  Leaf01Icon,
  LockIcon,
  Mail01Icon,
  Medal01Icon,
  Message01Icon,
  MicroscopeIcon,
  Moon02Icon,
  MountainIcon,
  MusicNote01Icon,
  Note01Icon,
  Notification01Icon,
  PaintBrush01Icon,
  PencilEdit01Icon,
  Pizza01Icon,
  PuzzleIcon,
  RoboticIcon,
  RocketIcon,
  SatelliteIcon,
  ServerStack01Icon,
  Shield01Icon,
  SmartPhone01Icon,
  SnowIcon,
  SparklesIcon,
  StarIcon,
  Sun03Icon,
  Target02Icon,
  TeaIcon,
  Telescope01Icon,
  Train01Icon,
  UmbrellaIcon,
  UserIcon,
  ViewIcon,
  WifiConnected01Icon,
  Wrench01Icon,
  ZapIcon,
} from "@src/icons";
import type { CustomRoleIconId } from "@src/types/userPresence";

export const CUSTOM_ROLE_ICONS: Record<CustomRoleIconId, IconSvgElement> = {
  user: UserIcon,
  briefcase: Briefcase01Icon,
  building: Building01Icon,
  home: Home01Icon,
  code: CodeXmlIcon,
  terminal: ComputerTerminal01Icon,
  computer: ComputerIcon,
  branch: GitBranchIcon,
  bug: Bug01Icon,
  wrench: Wrench01Icon,
  database: Database01Icon,
  server: ServerStack01Icon,
  chart: ChartLineData01Icon,
  pen: PencilEdit01Icon,
  note: Note01Icon,
  book: Book01Icon,
  bookmark: Bookmark01Icon,
  flag: Flag01Icon,
  rocket: RocketIcon,
  flame: FireIcon,
  zap: ZapIcon,
  idea: Idea01Icon,
  target: Target02Icon,
  brain: BrainIcon,
  eye: ViewIcon,
  shield: Shield01Icon,
  lock: LockIcon,
  key: Key01Icon,
  clock: Clock01Icon,
  calendar: Calendar03Icon,
  battery: BatteryFullIcon,
  coffee: Coffee01Icon,
  tea: TeaIcon,
  pizza: Pizza01Icon,
  headphones: HeadphonesIcon,
  music: MusicNote01Icon,
  game: GameController01Icon,
  camera: Camera01Icon,
  brush: PaintBrush01Icon,
  puzzle: PuzzleIcon,
  dumbbell: Dumbbell01Icon,
  gift: GiftIcon,
  trophy: ChampionIcon,
  medal: Medal01Icon,
  crown: CrownIcon,
  diamond: DiamondIcon,
  star: StarIcon,
  heart: FavouriteIcon,
  sparkles: SparklesIcon,
  message: Message01Icon,
  mail: Mail01Icon,
  bell: Notification01Icon,
  phone: SmartPhone01Icon,
  wifi: WifiConnected01Icon,
  satellite: SatelliteIcon,
  compass: CompassIcon,
  globe: Globe02Icon,
  plane: Airplane01Icon,
  train: Train01Icon,
  car: Car01Icon,
  bicycle: Bicycle01Icon,
  anchor: AnchorIcon,
  mountain: MountainIcon,
  sun: Sun03Icon,
  moon: Moon02Icon,
  cloud: CloudIcon,
  snow: SnowIcon,
  umbrella: UmbrellaIcon,
  leaf: Leaf01Icon,
  feather: FeatherIcon,
  telescope: Telescope01Icon,
  microscope: MicroscopeIcon,
  atom: AtomicPowerIcon,
  bot: BotIcon,
  robot: RoboticIcon,
  alien: Alien01Icon,
  ghost: GhostIcon,
};

export const CUSTOM_ROLE_ICON_IDS: readonly CustomRoleIconId[] = [
  "user",
  "briefcase",
  "building",
  "home",
  "code",
  "terminal",
  "computer",
  "branch",
  "bug",
  "wrench",
  "database",
  "server",
  "chart",
  "pen",
  "note",
  "book",
  "bookmark",
  "flag",
  "rocket",
  "flame",
  "zap",
  "idea",
  "target",
  "brain",
  "eye",
  "shield",
  "lock",
  "key",
  "clock",
  "calendar",
  "battery",
  "coffee",
  "tea",
  "pizza",
  "headphones",
  "music",
  "game",
  "camera",
  "brush",
  "puzzle",
  "dumbbell",
  "gift",
  "trophy",
  "medal",
  "crown",
  "diamond",
  "star",
  "heart",
  "sparkles",
  "message",
  "mail",
  "bell",
  "phone",
  "wifi",
  "satellite",
  "compass",
  "globe",
  "plane",
  "train",
  "car",
  "bicycle",
  "anchor",
  "mountain",
  "sun",
  "moon",
  "cloud",
  "snow",
  "umbrella",
  "leaf",
  "feather",
  "telescope",
  "microscope",
  "atom",
  "bot",
  "robot",
  "alien",
  "ghost",
] as const;

export function resolveCustomRoleIcon(id: CustomRoleIconId): IconSvgElement {
  return CUSTOM_ROLE_ICONS[id] ?? UserIcon;
}
